### ISSUE TITLE
I think docs need some update!

### ISSUE THREAD

**Issue by mamayadi** [moltin/moltin-request#102]
I want to create a whishlist to my customers,

I follow this [steps](https://developers.moltin.com/guides/custom-data/create-a-wishlist) and I am stack in the #8 step. How to get: `CUSTOMER_FLOW_ID`

Even when I add the wishlist it is not shown in the customers custome field there is no field added.
And one other think. Please add array filed in filed type in the flows filed I think this will solve a lot of problems.

And, We are waiting more tutorials from your youtube channel.

Thanks!

**Comment by matthew1809** [comment]
Hey @mamayadi! In step 7, the API response for creating the customer flow will have an ID in the body, that's the ID which you use in step 8 👍 Does that make sense? Here's the object in the documentation: https://docs.moltin.com/advanced/custom-data/flows#the-flow-object

**Comment by matthew1809** [comment]
Re. array field types, nice idea, we've been looking at a JSON field type which would help.

**Comment by notrab** [comment]
Thanks @matthew1809  I'm going to close this issue as it's not related to this package.

@mamayadi - More videos coming soon 😏 ❤️

**Comment by mamayadi** [comment]
@matthew1809 `"title": "customers is already in use"` what should I do in this case?
