### ISSUE TITLE
Feature request: Caching access_token 

### ISSUE THREAD

**Issue by johannzv** [moltin/moltin-request#11]
It would have been nice if valid access tokens somehow were stored, and used in subsequent requests.[https://github.com/moltin/moltin-request/blob/master/src/index.ts#L38](url).

**Comment by notrab** [comment]
Hey @johannzv 

It's something I'm looking to implement shortly, with the option for providing custom storage, so we can replace the mechanics of the main JS SDK with this package.

**Comment by notrab** [comment]
@johannzv 

I have a PR open (yet to be approved/merged): https://github.com/moltin/moltin-request/pull/93 that fixes this issue.
