### ISSUE TITLE
How to POST a file?

### ISSUE THREAD

**Issue by mamayadi** [moltin/moltin-request#119]
I have a Blob object and I want to send it to server.
Here is my code based on your [docs](https://docs.moltin.com/api/advanced/files/create-a-file):
`
const formData = new FormData();
formData.append("file_name", productName);
formData.append("public", "true");
formData.append("mime_type", "image/png");

canvas.toBlob(blob => { 
formData.append("file", blob, productName);
});

const headers = {
          "Content-Type": "image/png"
        };
const data = {
          body: formData
        };
moltin
          .post("files", data, headers)
          .then(data => console.log(data))
          .catch(err => console.error(err));
`

I am always getting `{status: 500, title: "InternalError", detail: "Cannot read property 'file' of undefined", request_id: "xxx..."}`

Any solution please!

Thanks in  advance!

**Comment by notrab** [comment]
Sorry this went unnoticed @mamayadi 

The docs appear to be incorrect and I'll make sure they're fixed.

The `Content-Type` *must* be `multipart/form-data` as outlined [here](https://docs.moltin.com/api/basics/content-type).

`file` in the example below must be your file from your form.

```js
const { MoltinClient } = require('@moltin/request')
const FormData = require("form-data")
​
const moltin = new MoltinClient({
  client_id: 'X',
  client_secret: 'X'
})
​
const formData = new FormData()
​
formData.append("public", true)
formData.append("file", file)

moltin
  .post("files", formData, { "Content-Type": "multipart/form-data" } )
  .then(console.log))
  .error(console.error)
```

Perhaps @matthew1809 or @gje4 have a more up to date file upload example than this original extract from one of their projects.
