### ISSUE TITLE
request_1.MoltinClient is not a constructor

### ISSUE THREAD

**Issue by matthew1809** [moltin/moltin-request#128]
Using version 2.0.0 with the following code:

```
import { MoltinClient } from '@moltin/request'

const client = new MoltinClient({
    client_id: process.env.MOLTIN_CLIENT_ID,
    client_secret: process.env.MOLTIN_CLIENT_SECRET
})
```

**Comment by notrab** [comment]
@matthew1809 Are you able to `rm -rf node_modules` and rerun `yarn`?

Also, double check you don't have the package linked with npm/yarn to a stale local build.

Works first time for me in a new app: https://codesandbox.io/embed/icy-http-oljdy

**Comment by notrab** [comment]
Closing as stale - please reopen if the issue persists.
